menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/sunchongsheng
    GitHub: https://github.com/pinggod
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics (Google Analytics 4)
# ga: G-XXXXXXXXXX

# Copyright Infomation
startyear: 2015
